#!/usr/bin/env bash
# Rebuild EVM-targeted UltraHonk artifacts from the policy circuit.
# Run from the repository root after changing circuits/policy.
# HonkVerifier.sol and the allow fixture must be produced by the same bb as
# live `bb prove` (Anvil demo); otherwise verify reverts SumcheckFailed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=/dev/null
source "$ROOT/scripts/toolchain.env"
CIRCUIT="$ROOT/circuits/policy"
CONTRACTS="$ROOT/contracts"
export PATH="${HOME}/.foundry/bin:${HOME}/.nargo/bin:${HOME}/.bb:${PATH}"

need_pin() {
  local name="$1" expected="$2" got
  got="$("$name" --version 2>/dev/null | head -n 1 || true)"
  if ! grep -q "$expected" <<<"$got"; then
    echo "expected $name ${expected}, got: ${got:-missing}" >&2
    echo "install with noirup -v ${NOIR_VERSION} / bbup -v ${BB_VERSION}" >&2
    exit 1
  fi
}

need_pin nargo "$NOIR_VERSION"
need_pin bb "$BB_VERSION"
echo "toolchain: nargo ${NOIR_VERSION} / bb ${BB_VERSION}"

cd "$CIRCUIT"
nargo execute
bb write_vk -b ./target/policy.json -o ./target --verifier_target evm
bb prove -b ./target/policy.json -w ./target/policy.gz -o ./target -k ./target/vk \
  --verifier_target evm --verify

tmp="$(mktemp)"
bb write_solidity_verifier -k ./target/vk -o "$tmp" --verifier_target evm
mkdir -p "$CONTRACTS/src/verifier"
{
  echo "// SPDX-License-Identifier: Apache-2.0"
  echo "// Generated by bb ${BB_VERSION} write_solidity_verifier (UltraHonk, --verifier_target evm)."
  echo "// Do not edit by hand. Regenerate with scripts/export-evm-artifacts.sh after circuit changes."
  tail -n +2 "$tmp"
} >"$CONTRACTS/src/verifier/HonkVerifier.sol"
rm -f "$tmp"

mkdir -p "$CONTRACTS/test/fixtures"
python3 - <<PY
from pathlib import Path
root = Path("$CIRCUIT")
out = Path("$CONTRACTS/test/fixtures")
proof = (root / "target/proof").read_bytes()
pubs = (root / "target/public_inputs").read_bytes()
(out / "allow.proof.bin").write_bytes(proof)
fields = ["0x" + pubs[i * 32:(i + 1) * 32].hex() for i in range(len(pubs) // 32)]
(out / "allow.public_inputs.hex").write_text("\n".join(fields) + "\n")
print(f"wrote {out / 'allow.proof.bin'} ({len(proof)} bytes)")
print(f"wrote {len(fields)} public inputs")
PY
